server:
  port: 8888


spring:
  application:
    name: ServerConfig
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AsmaaAchkal/TpMicroservices-config
          clone-on-start: true
          # default-label: master
          # search-paths: configFiles

  # security:
  #   user:
  #     password: admin
  #     name: admin
